knative/serving-operator

OWNERS
and reviewers
/cc bbrowning, greghaynes
=> Add OWNERS file to define initial set of approvers

test/presubmit-tests.sh
=> Add the script presubmit-tests.sh in order to launch the prow jobs

pkg/controller/knativeserving/knativeserving_controller.go
Follow up from #23 to support applying the custom resource.
=> Use KO_DATA_PATH for custom resource

test/e2e-tests.sh
=> Re-enable integration tests

pkg/controller/knativeserving/knativeserving_controller.go
I found these logs helpful for debugging. Happy to keep or discard.
=> Increase logging for knativeserving controller

OWNERS
As discussed at WG meeting - lets add Thomas as an approver!
=> Add trshafer as approver

OWNERS
As discussed at WG meeting - lets add Vincent as an approver!
=> Add houshengbo as approver

config/crds/serving_v1alpha1_knativeserving_cr.yaml
This reverts commit dcd72a436d2df88cdf168211ad2616a700fb67a1.
=> Revert "Update default CR with knative-serving namespace. (#55)"

cmd/manager/main.go, pkg/reconciler/controller.go, pkg/reconciler/knativeserving/common/extensions.go, pkg/reconciler/knativeserving/knativeserving_controller.go, pkg/reconciler/knativeserving/minikube/minikube.go, pkg/reconciler/knativeserving/openshift/openshift.go
=> Access the resources with kubeclient and dynamicclient

pkg/reconciler/knativeserving/knativeserving_controller.go, pkg/reconciler/knativeserving/minikube/minikube.go, pkg/reconciler/knativeserving/openshift/openshift.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
/assign @mattmoor
=> golang format tools

pkg/reconciler/knativeserving/knativeserving_controller.go
=> Relax name[space] constraints

pkg/reconciler/knativeserving/knativeserving_controller.go
Add additional logging in the check step of the controller.
This will make the diff in https://github.com/knative/serving-operator/pull/84 more clear.
Small refactor
```release-note
NONE
```
=> Refactor applying the resources to a helper function.

pkg/reconciler/knativeserving/knativeserving_controller.go
Produced via:
`github.com/client9/misspell`
/assign @mattmoor
=> Fix spelling errors

test/README.md, test/cleanup.go, test/clients.go, test/crd.go, test/e2e/e2e.go, test/e2e/knativeservingdeployment_test.go, test/e2e_flags.go, test/resources/knativeserving.go
* This PR adds the test case to create the knativeserving under a specified test namespace.
* Verify the deployment recreation under the test namespace.
* Verify the deletion of knativeserving.
```release-note
```
=> Add test cases to verify the creation of KnativeServing 🧗‍♂️

test/e2e/knativeservingdeployment_test.go
Since the operator creates them all the same way, if one works they
all will, and the test will run much faster.
=> Speed up the tests by only deleting one deployment

pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
This should've been removed in PR #106
=> Remove unused MarkIgnored lifecycle function

Gopkg.lock, pkg/reconciler/knativeserving/knativeserving_controller.go, vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go, vendor/github.com/aws/aws-sdk-go/aws/version.go
Co-authored-by: Markus Thömmes \<markusthoemmes@me.com\>
* This PR replaces the clients of controller-runtime with either KS client or kubeclient.
```release-note
```
=> Remove clients of controller-runtime except InjectClient func 🧗‍♂️

hack/generate-yamls.sh
=> [Release]Cherry pick 0fefbb9 for fixing generate-yamls

hack/generate-yamls.sh
=> [Release]Cherry pick 8a0703a for adding trace in generate-yamls

test/e2e/knativeservingdeployment_test.go
Fixes #
* Instead of checking that just deployments are removed, check that all resources deployed by the operator are removed when KnativeServing CR is removed
* Add more tests for updating KnativeServing and propagating the changes to the target config map:
- delete a single key/value pair
- use an empty map as the value
```release-note
```
=> Additional tests for resource deletion and update

test/e2e-common.sh
* This PR makes sure the pod of the operator is running, before test case is running.
```release-note
```
=> Make sure the pod of the operator is running, before test case is running

cmd/manager/kodata/knative-serving/0.10.0.yaml, version/version.go
Fixes #
* adding the `serving.yaml` from the latest release (`v0.10.0`) to here
```release-note
```
=> Update to 0.10 release 

README.md
The latter won't work with the yaml
=> In the README, refer to a nightly build instead of the openshift fork

test/e2e-tests-latest-serving.sh
* This PR will help us find the commit ID directly, if the periodic prow job fails on a certain commit of serving.
```release-note
```
=> Add the marker of the latest commit ID for better debugging

pkg/reconciler/knativeserving/common/images.go, pkg/reconciler/knativeserving/common/images_test.go
=> Propagating configured imagePullSecrets to the Image

cmd/manager/kodata/knative-serving/0.11.0.yaml, version/version.go
Fixes #
* updates for shipping next upstream knative serving release 
*
*
```release-note
```
=> Updates to ship 0.11.0 releae of knative-serving

hack/boilerplate/boilerplate.go.txt
* As we move into the year of mouse, update the year to 2020 in the template.
```release-note
```
=> Update the year of the copyright to 2020 in the template

README.md, doc/upgrade_guide.md
Produced via:
`prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
/assign k4leung4
/cc k4leung4
=> Format markdown

deploy/olm-catalog/knative-serving-operator/0.12.0/300-serving-v1alpha1-knativeserving-crd.yaml, deploy/olm-catalog/knative-serving-operator/0.12.0/knative-serving-operator.v0.12.0.clusterserviceversion.yaml, deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
Fixes #
* OLM metadata for 0.12.0
* OLD CRD is not included in the CSV
*
```release-note
NONE
```
=> OLM metadata for 0.12.0

cmd/manager/kodata/knative-serving/0.12.1.yaml, version/version.go
* This PR updates the manifest of Knative Serving into version 0.12.1.
```release-note
```
=> Update the manifest of Knative Serving from 0.12.0 to 0.12.1

cmd/manager/kodata/knative-serving/0.12.1.yaml, version/version.go
* This PR cherry-picks the commit for 0.12.1.
```release-note
```
=> Update the manifest of Knative Serving from 0.12.0 to 0.12.1 (#272)

Gopkg.lock, vendor/github.com/jcrossley3/manifestival/transform.go
Fixes #283 
```release-note
Fixed namespace injection for RoleBindings and APIServices
```
=> Pull in manifestival fix for #283 from @houshengbo

test/e2e-common.sh
Fixes #
*
*
*
```release-note
```
=> Update the version of Istio to 1.4-latest

Gopkg.lock, pkg/client/injection/client/client.go, pkg/client/injection/client/fake/fake.go, pkg/client/injection/informers/factory/factory.go, pkg/client/injection/informers/factory/fake/fake.go, pkg/client/injection/informers/serving/v1alpha1/knativeserving/fake/fake.go, pkg/client/injection/informers/serving/v1alpha1/knativeserving/knativeserving.go, vendor/knative.dev/test-infra/scripts/README.md, vendor/knative.dev/test-infra/scripts/library.sh, vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc, vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign houshengbo k4leung4
/cc houshengbo k4leung4
=> Auto-update dependencies

Gopkg.lock, vendor/knative.dev/pkg/metrics/exporter.go
=> Fix prometheus metric nams

minikube-operator-example/config/operator.yaml
My initial grepping missed this.
=> Switch example images to strict mode

Gopkg.lock, vendor/knative.dev/test-infra/scripts/release.sh
/assign @houshengbo  @chizhg @k4leung4
=> [release-0.13]Update test-infra for release hotfix

Gopkg.lock, test/e2e-upgrade-tests.sh, vendor/knative.dev/test-infra/scripts/release.sh
Fixes #
*
*
*
```release-note
```
=> Update test-infra for release hotfix

cmd/manager/kodata/knative-serving/0.13.1.yaml, version/version.go
Fixes #
*
*
*
```release-note
```
=> Update the manifest to 0.13.1

cmd/manager/kodata/knative-serving/serving.yaml, version/version.go
Fixes #
*
*
*
```release-note
```
=> Update the manifest to the latest nightly build

OWNERS
I would like to help contribute to the project by reviewing PRs.
I believe I've reviewed the timeliness requirements
and am willing to put forward a good faith effort to meet them :)
I don't know if the capitalization of the github username is needed
happy to remove if not.
```release-note
NONE
```
=> Add Cynocracy to reviewers.

Gopkg.lock, vendor/knative.dev/pkg/Gopkg.lock, vendor/knative.dev/pkg/Gopkg.toml, vendor/knative.dev/pkg/injection/sharedmain/main.go, vendor/knative.dev/pkg/leaderelection/config.go, vendor/knative.dev/pkg/test/helpers/dir.go, vendor/knative.dev/pkg/test/performance/performance.go, vendor/knative.dev/pkg/test/testgrid/testgrid.go, vendor/knative.dev/pkg/webhook/admission.go, vendor/knative.dev/pkg/webhook/configmaps/configmaps.go, vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go, vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go, vendor/knative.dev/pkg/webhook/webhook.go, vendor/knative.dev/test-infra/scripts/e2e-tests.sh, vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Produced via:
`./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign houshengbo k4leung4
/cc houshengbo k4leung4
=> [master] Auto-update dependencies

cmd/manager/kodata/knative-serving/serving.yaml, version/version.go
Fixes #
*
*
*
```release-note
```
=> Update the manifest to the nightly built version

config/role.yaml
* Allow the operator to start/stop/watch/list Jobs
Potentially unblocks #399
```release-note
```
=> Allow Operator to use Jobs as part of upgrades.

config/role.yaml
Fixes #
*
*
*
```release-note
```
=> Also allow job updates.

deploy/olm-catalog/knative-serving-operator/0.13.1/knative-serving-operator.v0.13.1.clusterserviceversion.yaml, deploy/olm-catalog/knative-serving-operator/0.13.1/knativeservings.operator.knative.dev.crd.yaml, deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
Fixes #
* OLM metadata for 0.13.1
*
*
```release-note
NONE
```
=> OLM metadata for 0.13.1
