knative/serving-operator

config/operator.yaml
This is overriding the exec reference ko creates
=> Remove comand from operator container

README.md, hack/release.md
Produced via:
`prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`
/assign @mattmoor
=> Format markdown

pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
This makes all receiver names consistent in this file. 
The only remaining lint errors are docs.
=> Address receiver name lint error

cmd/manager/kodata/knative-serving/0.7.0.yaml, version/version.go
I validated this by deploying the old version of 0.6.0 using the operator and then deploying 0.7.0 using the operator on GKE.
I did not delete the 0.6.0 yaml files.
=> Update operator to install knative serving 0.7.0

README.md, hack/run-local.sh
This will pick up the default kubeconfig and run the operator outside
of the cluster as a remote client, handy for development:
```
$ ./hack/run-local.sh --help
$ ./hack/run-local.sh
$ ./hack/run-local.sh --zap-devel
$ ./hack/run-local.sh --zap-devel --zap-level info
```
I'm hoping the script can be converted to use the knative controller
when that drops.
=> A simple script to run the operator locally

config/crds/serving_v1alpha1_knativeserving_cr.yaml
knative-serving is the namespace used by the knativeserving controller to look
up the KnativeServing CR.
I'm not sure if there should be another change to add a namespace to knativeserving_controller: https://github.com/knative/serving-operator/blob/94e6137bb6df889c3a386435ab80a390ba66419b/pkg/controller/knativeserving/knativeserving_controller.go#L309.
=> Update default CR with knative-serving namespace.

config/crds/serving_v1alpha1_knativeserving_crd.yaml, pkg/apis/serving/v1alpha1/knativeserving_types.go, pkg/controller/knativeserving/common/extensions.go, pkg/controller/knativeserving/common/gateway.go, pkg/controller/knativeserving/common/gateway_test.go
Adds a new API to KnativeServing:
spec:
knative-ingress-gateway:
selector:
istio: "new-istio-selector"
Fixes #50
=> Add ability to update the KnativeIngressGateway istio selector

pkg/reconciler/knativeserving/common/config_maps.go, pkg/reconciler/knativeserving/common/extensions.go, pkg/reconciler/knativeserving/common/gateway.go, pkg/reconciler/knativeserving/common/gateway_test.go, pkg/reconciler/knativeserving/common/images.go, pkg/reconciler/knativeserving/common/images_test.go, pkg/reconciler/knativeserving/minikube/minikube.go
Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`
/assign @mattmoor
=> golang format tools

Gopkg.lock, cmd/manager/main.go, config/operator.yaml, hack/run-local.sh
WATCH_NAMESPACE is an artifact of operator-sdk. As we're moving over to pkg/controller, we don't need this anymore.
=> Remove 'WATCH_NAMESPACE' functionality.

.github/pull-request-template.md
We have these in other repos as well, so this makes things more even. it also includes running lint usually, to find out linting issues early.
=> Add a pull-request template so we almost always automatically run /lint.

pkg/reconciler/knativeserving/knativeserving_controller.go
This piece of code is intended to prevent us from reapplying the full YAML if we're already in a deploying state. It can cause us to not recreate deployments though if we end up in an interim state, i.e. we're already in a deploying state and deployments start to vanish. We will never reconcile that in that case because this piece of code will always say that we're deploying and the checkDeployments code will never tell us something different.
Reapplying the YAML in any case is benign anyway. We can be smarter about this later and check the spec of what's already applied against the spec of the YAML in the file. That's purely a performance optimization though, correctness should not be affected by that.
/assign @houshengbo @jcrossley3
=> Remove short-circuiting installation logic if we're in an installing state.

pkg/reconciler/knativeserving/common/extensions.go, pkg/reconciler/knativeserving/knativeserving_controller.go, pkg/reconciler/knativeserving/minikube/minikube.go
We'll leave the minikube extension in for now, just as a reminder that
we need something, but openshift is gone.
I change the args a bit, and they'll likely evolve... or not, if we move all extension stuff out of the repo.
See https://docs.google.com/document/d/1OtlkJ8whTgHYTz5rz0lq5mNdDGK_pakG/edit
=> Simplify extension logic in anticipation of ripping it out entirely

pkg/reconciler/knativeserving/common/extensions.go, pkg/reconciler/knativeserving/common/gateway.go, pkg/reconciler/knativeserving/common/gateway_test.go, pkg/reconciler/knativeserving/common/images.go, pkg/reconciler/knativeserving/common/images_test.go, pkg/reconciler/knativeserving/knativeserving_controller.go
The `scheme` is used nowhere in our code today and I'd keep it that way.
=> Remove 'scheme'.

config/operator.yaml
create DynamicRestMapper failed because kube apiserver couldn't be reached during startup.
Signed-off-by: Wei Yu <yuweiw@cn.ibm.com>
```
root@filmy1:/mnt/data/gowork/src/knative.dev/serving-operator# kubectl logs -f -c knative-serving-operator knative-serving-operator-7ff9bf4cd6-7zzqj
2019-08-08T08:07:00.112Z	ERROR	kubebuilder.manager	Failed to get API Group-Resources	{"error": "Get https://10.0.0.1:443/api?timeout=32s: dial tcp 10.0.0.1:443: connect: connection refused"}
knative.dev/serving-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error
/mnt/data/gowork/src/knative.dev/serving-operator/vendor/github.com/go-logr/zapr/zapr.go:128
knative.dev/serving-operator/vendor/sigs.k8s.io/controller-runtime/pkg/manager.New
/mnt/data/gowork/src/knative.dev/serving-operator/vendor/sigs.k8s.io …
```
=> serving operator crashed during startup because connection to api server is not ready

cmd/manager/kodata/knative-serving/0.8.0.yaml, version/version.go
* Updates to the most recent 0.8.0 knative serving: https://github.com/knative/serving/releases/download/v0.8.0/serving.yaml
```release-note
Update installation to the most recent 0.8.0 knative serving.
```
=> Update knative serving to 0.8.0

Gopkg.lock, pkg/reconciler/knativeserving/knativeserving_controller.go, vendor/github.com/jcrossley3/manifestival/manifestival.go
Fixes #147
This makes it possible to use https://github.com/go-logr/zapr to create a `logr.Logger` impl from `pkg/logging`
=> Update manifestival to accept a logr.Logger

Gopkg.lock, test/clients.go, test/config/0.8.0.yaml, test/e2e/knativeservingdeployment_test.go
Fixes #152
* Add the verification of the cluster-scoped resource deletion, if the CR is deleted.
```release-note
```
=> Add the verification of cluster-scoped resource deletion

pkg/reconciler/knativeserving/controller.go, pkg/reconciler/knativeserving/knativeserving_controller.go, test/cleanup.go, test/clients.go, test/e2e/e2e.go, test/e2e/knativeservingdeployment_test.go
Fixes #154 
Strictly speaking, it doesn't address what it means to have multiple `KnativeServing` resources, because having them isn't necessarily a problem. The problem occurs when any one of them is deleted, at which point (prior to this change) all the cluster-scoped resources are deleted, thereby breaking all the remaining KS installations.
With this fix, the shared resources are only deleted when the last KS is deleted.
=> Only delete shared resources when last KS is deleted

config/crds/serving_v1alpha1_knativeserving_crd.yaml, pkg/apis/serving/v1alpha1/knativeserving_types.go, pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go, pkg/reconciler/knativeserving/common/gateway_test.go, pkg/reconciler/knativeserving/common/images.go, pkg/reconciler/knativeserving/common/images_test.go
Fixes #124 
* Adds support for specifying imagePullSecrets for a private registry.
* The secrets are specified in the same format they would be on a Deployment
* The secret needs to be created in the knative-serving namespace in order to work
I attempted to minimize duplication in the tests by doing a small amount of refactoring as I was reusing examples.
```release-note
Add support for providing imagePullSecrets when using a private registry for the knative images.
```
=> Adding support for imagePullSecrets

hack/generate-yamls.sh
grep returns 1 if there is no match, which is the case since there is only 1 file generated, which was negated by `-v`. Fixing it by ignoring grep error
/cc @k4leung4
=> Fix generate-yamls error by Ignoring grep error

pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go, pkg/apis/serving/v1alpha1/knativeserving_lifecycle_test.go, pkg/apis/serving/v1alpha1/register.go, pkg/apis/serving/v1alpha1/register_test.go, pkg/reconciler/knativeserving/knativeserving_controller.go
Fixes #
* The CR KnativeServing can have a default GroupVersionKind, so that we do not need to set it in the reconcile function.
```release-note
```
=> Set the default GroupVersionKind for KnativeServing

test/e2e/knativeservingdeployment_test.go
* This PR skips the namespace check, because the namespace in the Manifest can be overwritten by injected namespace. When the CR is deleted, the original namespace can still exist.
```release-note
```
=> Skip the namespace check for integration test

hack/generate-yamls.sh
While `|| true` also works, it's easy to miss that and swallow errors in the future when more YAMLs are added.
=> Comment extra YAML listing until they're available

config/config-logging.yaml
I believe this file was copied from knative-serving and these
examples could give the impression that the knative-serving logging
configuration can be changed from the operator's config-logging,
which isn't the case.
* Remove logging configuration examples which could be confusing/misleading
```release-note
```
=> Removing logging override examples from config-logging.yaml

test/config, test/config/0.8.0.yaml, test/e2e-common.sh, test/e2e-tests-latest-serving.sh, test/e2e-tests.sh
Fixes #188 
* Added a new script called e2e-tests-latest-serving.sh, to run the operator installation with the latest generated manifest of knative serving, and run the integration tests against the Kube cluster. This script will be called directly by a periodic prow job.
```release-note
```
=> Add a new script to test the latest generated manifest of knative serving

pkg/reconciler/knativeserving/common/gateway_test.go, pkg/reconciler/knativeserving/common/images.go, pkg/reconciler/knativeserving/common/images_test.go
I think this is "The Right Way" to do it, but I could be wrong. Makes
the code a bit smaller anyway.
Fixes https://github.com/knative/serving-operator/pull/20#discussion_r297817556
=> Clean up the [un]structured conversions a bit

README.md
* describe how to run an actual release, instead of nightly
=> Applying a released version of the operator

pkg/reconciler/knativeserving/knativeserving_controller.go
Otherwise, updating an existing `KnativeServing` resource in a way that makes any of the transformations fail will cause the operator to retry indefinitely, but the status of the `KnativeServing` CR will continue to show `Ready`.
=> We need to fail the install if any transforms error

version/version_test.go
Fixes #201 
Ported from eventing operator, https://github.com/knative/eventing-operator/pull/42
* Add a test that compares the version in `version.go` and the `serving.knative.dev/release` labels for resources in Knative serving YAML
```release-note
NONE
```
=> Add test for version consistency

Gopkg.lock, Gopkg.toml, vendor/github.com/jcrossley3/manifestival/manifestival.go, vendor/github.com/jcrossley3/manifestival/transform.go, vendor/github.com/jcrossley3/manifestival/yaml.go
Back on the `client-go` branch, with immutable transforms merged, some edgecase filesystem fixes (thanks @houshengbo), lint-free comments, and proper handling of injected namespaces in webhook resources (thanks @evankanderson)
=> Update to latest manifestival

pkg/reconciler/knativeserving/knativeserving_controller.go, test/e2e/knativeservingdeployment_test.go
This should be more predictable and thread-safe, i.e. The Right Way.
* Delete manifest resources in a finalizer instead of after the `KnativeServing` resource is already gone.
=> Delete manifest resources in a finalizer

pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go, pkg/apis/serving/v1alpha1/knativeserving_lifecycle_test.go, pkg/apis/serving/v1alpha1/knativeserving_types.go
This allows any other controllers, e.g. platform-specific ones, watching the KnativeServing resource to defer its "Ready" condition until any deps on that platform, e.g. a service mesh, are successfully installed.
This is effectively a no-op unless some other controller marks the condition as "missing" or "installing".
=> Add a "DependenciesInstalled" condition that defaults to true

.gitignore, hack/update-deps.sh, test/e2e_flags.go
* *Letting flags be changed from outside*
Changing those flags is needed to perform tests on RH operators.
* *Adding Intellij, and vandors excluded files to gitignore*
This PR let change test flags from outside. It can be done either by:
* declaring environmental variables: `TEST_NAMESPACE`, and `TEST_RESOURCE`,
* using `-ldflags "-X knative.dev/serving-operator/test.ServingOperatorNamespace=knative-serving"`
```release-note
NONE
```
=> Letting flags be changed from outside 

pkg/reconciler/knativeserving/controller.go, pkg/reconciler/knativeserving/knativeserving_controller.go, pkg/reconciler/reconciler.go, pkg/reconciler/reconciler_test.go, pkg/reconciler/stats_reporter.go, pkg/reconciler/stats_reporter_test.go
Serving operator can emit metrics on KnativeServing CR edits, including creation, modification and deletion.
Steps to test metrics with Prometheus exporter (default):
1. Forward the local port 9090 to the port 9090 on operator pod by running
`kubectl port-forward ${{operator_pod_name}} 9090`
2. Check the metrics by visiting `localhost:9090/metrics`
```release-note
NONE
```
=> Add metrics about KnativeServing CR edits

Gopkg.lock, pkg/reconciler/knativeserving/common/certs.go, pkg/reconciler/knativeserving/common/images.go, third_party/VENDOR-LICENSE, vendor/github.com/jcrossley3/manifestival/manifestival.go, vendor/github.com/jcrossley3/manifestival/patch/patch.go, vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
Fixes #226 #202 #160 
Makes things a little more straightforward to implement whatever direction comes from #163 
* The latest manifestival performs the same strategic merging used by `kubectl apply`
* Except for `ConfigMap` -- any change to the `KnativeServing` config entries will overwrite the corresponding ConfigMaps
* Superfluous updates of `Deployment` and `Image` resources should be fixed
* Diffs are now logged so it's easier to see why a resource is being updated
```release-note
The serving operator will now apply [strategic merging](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merge-patch-calculation) of its resources to any changes made that aren't a part of its embedded manifest should not be overwritten.
```
=> Update to latest manifestival to apply strategic merge patches to its resources.

config/300-serving-v1alpha1-knativeserving-crd.yaml
* This PR removes the short name for the Knative Serving Operator CRD, since this is the decision made in operation WG.
```release-note
```
=> Remove the short name for consistent decision in Operation WG

cmd/manager/kodata/knative-serving/0.11.1.yaml, version/version.go
* This PR is a update of the manifest for Knative Serving from 0.11.0 to 0.11.1, in order to cut the release of 0.11.1 for serving operator.
```release-note
```
=> Update the released YAML to 0.11.1 for Knative Serving

.gitignore, README.md, deploy/olm-catalog/knative-serving-operator/0.11.0/knative-serving-operator.v0.11.0.clusterserviceversion.yaml, deploy/olm-catalog/knative-serving-operator/0.11.0/knativeservings.operator.knative.dev.crd.yaml, deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml, hack/generate-olm-catalog-source.sh
Fixes #261 
* Check in OLM metadata. That is to be submitted to OperatorHub
* Check in `hack/generate-olm-catalog-source.sh`. This is to generate OLM catalog source from OLM metadata and thus to test the operator with OLM.
* Add documentation in README around how to test OLM integration
```release-note
NONE
```
Verification instructions on Minikube:
* Install OLM : https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md
* Create the `CatalogSource` using the instructions in the modified README
* Install the operator using one of:
A. Create operator subscription using the instructions in the modified README 
B. Optional: [run OLM console locally](https://github.com/operator-framework/operator-lifecycle-manager#user-interface) …
=> OLM metadata

README.md, doc/upgrade_guide.md
Fixes #
*
*
*
```release-note
```
=> Add the instruction on how to upgrade v0.10 and v0.11 to v0.12

test/e2e/knativeservingdeployment_test.go
This makes a tiny change that knativeServingDelete prints missing error message.
Currently the error prints as:
```
--- FAIL: TestKnativeServingDeployment/delete (30.65s)
knativeservingdeployment_test.go:244: The CustomResourceDefinition ingresses.networking.internal.knative.dev failed to be deleted
```
and it is difficult to find the reason why `clients.Dynamic.Resource(gvrs).Get()` failed to delete.
/lint
```release-note
NONE
```
=> Print error in knativeServingDelete

config/role.yaml
Unfortunately it appears that in order to use an aggregated
clusterrole we need the operator to be a cluster-admin.
This should help prevent confusion re: why we have both an
explicit list and a blanket `*/*` granted to the operator
service account.
See #282 
* Add a (hopefully) helpful comment.
NONE
=> Add a comment about why cluster-admin is necessary.

pkg/reconciler/knativeserving/common/certs_test.go, pkg/reconciler/knativeserving/common/extensions.go, pkg/reconciler/knativeserving/common/images.go, pkg/reconciler/knativeserving/common/images_test.go
Fixes https://github.com/knative/serving-operator/issues/280
* Extended image override logic for DaemonSet when there is image update by [override](https://github.com/savitaashture/serving-operator/blob/master/pkg/apis/serving/v1alpha1/knativeserving_types.go#L47) 
This PR will be validated when release manifest updated to changes from knative/serving#6624
This PR has dependency [knative.dev/pkg](https://github.com/knative/pkg/pull/1043)
=> Add image override logic for DaemonSet

cmd/manager/main.go, pkg/reconciler/knativeserving/controller.go
Fixes #292 
* Backwards compatible change
* Only use `KUBECONFIG` if the command line argument is empty
```release-note
NONE
```
Same PR for eventing operator: https://github.com/knative/eventing-operator/pull/100
=> Support reading KubeConfig from KUBECONFIG env var

Gopkg.lock, Gopkg.toml, pkg/reconciler/knativeserving/controller.go, pkg/reconciler/knativeserving/knativeserving_controller.go, test/resources/verify.go, third_party/VENDOR-LICENSE, vendor/github.com/go-logr/logr/testing/null.go, vendor/github.com/go-logr/logr/testing/test.go, vendor/github.com/manifestival/client-go-client/LICENSE, vendor/github.com/manifestival/client-go-client/client.go, vendor/github.com/manifestival/manifestival/client.go, vendor/github.com/manifestival/manifestival/manifestival.go, vendor/github.com/manifestival/manifestival/options.go, vendor/github.com/manifestival/manifestival/transform.go, vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
This introduces support for different client implementations, e.g.
client-go and controller-runtime. This repo uses client-go so that
requires a dependency on the repo implementing the client-go
manifestival client.
=> Update to Manifestival v0.1.0

Gopkg.lock, Gopkg.toml, pkg/reconciler/knativeserving/knativeserving_controller.go, test/resources/verify.go, vendor/github.com/manifestival/client-go-client/client.go, vendor/github.com/manifestival/manifestival/client.go, vendor/github.com/manifestival/manifestival/filter.go, vendor/github.com/manifestival/manifestival/manifestival.go, vendor/github.com/manifestival/manifestival/options.go, vendor/github.com/manifestival/manifestival/source.go, vendor/github.com/manifestival/manifestival/sources/path.go, vendor/github.com/manifestival/manifestival/sources/yaml.go, vendor/github.com/manifestival/manifestival/transform.go, version/version_test.go
This brings in several API enhancements and bug fixes. In particular,
the Filter function makes it easy to prevent the deletion of CRD
resources when the KS CR is deleted. We can make that change in a
separate PR once this one's merged.
=> Update to manifestival 0.2.0

pkg/reconciler/knativeserving/knativeserving_controller.go, test/resources/verify.go
Fixes #307 
* No longer deleting CRD's
```release-note
The operator will no longer remove `*.knative.dev` CRD's when uninstalling knative-serving.
```
=> No longer deleting CRD's when KnativeServing is deleted

deploy/olm-catalog/knative-serving-operator/0.12.2/knative-serving-operator.v0.12.2.clusterserviceversion.yaml, deploy/olm-catalog/knative-serving-operator/0.12.2/knativeservings.operator.knative.dev.crd.yaml, deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
Fixes #
* OLM metadata for 0.12.2
```release-note
NONE
```
OperatorHub PR is already merged: https://github.com/operator-framework/community-operators/pull/1280
Note: we had to skip 0.12.1 as it had a bug that was causing some problems with OperatorHub verification tests
=> OLM metadata for 0.12.2

test/README.md, test/e2e-common.sh, test/e2e-tests.sh, test/e2e-upgrade-tests.sh, test/e2e_flags.go, test/resources/knativeserving.go, test/resources/verify.go, test/upgrade/servingoperator_postupgrade_test.go, test/upload-test-images.sh
Fixes #310
* This PR adds the execution of upgrade and downgrade tests into the operator prow job.
* This PR refactors the e2e-common script, to accommodate the changes in upgrade tests.
* This PR adds the deployment verification for Knative in operator's upgrade tests. 
```release-note
```
=> Run the upgrade and downgrade tests in the upgrade prow job

OWNERS
Feel free to ping me directly if my review is desired on a PR. But, removing myself from OWNERS so the bot can make better auto-assignment of reviewers and approvers.
=> Remove myself from approvers/reviewers

config/300-serving-v1alpha1-knativeserving-crd.yaml, config/operator.yaml, config/role.yaml, config/role_binding.yaml, deploy/olm-catalog/knative-serving-operator/0.11.0/knative-serving-operator.v0.11.0.clusterserviceversion.yaml, deploy/olm-catalog/knative-serving-operator/0.11.0/knativeservings.operator.knative.dev.crd.yaml, deploy/olm-catalog/knative-serving-operator/0.12.0/300-serving-v1alpha1-knativeserving-crd.yaml, deploy/olm-catalog/knative-serving-operator/0.12.0/knative-serving-operator.v0.12.0.clusterserviceversion.yaml, deploy/olm-catalog/knative-serving-operator/0.12.2/knative-serving-operator.v0.12.2.clusterserviceversion.yaml, deploy/olm-catalog/knative-serving-operator/0.12.2/knativeservings.operator.knative.dev.crd.yaml, deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml, hack/boilerplate/add-boilerplate.sh, hack/boilerplate/boilerplate.go.txt, hack/boilerplate/boilerplate.yaml.txt, minikube-operator-example/config/operator.yaml, minikube-operator-example/config/role.yaml, minikube-operator-example/config/role_binding.yaml, minikube-operator-example/config/service_account.yaml, pkg/reconciler/knativeserving/common/gateway.go
This patch adds `add-boilerplate.sh` which is copied from serving
project and run to add missing license header:
```
bash hack/boilerplate/add-boilerplate.sh go pkg/
bash hack/boilerplate/add-boilerplate.sh yaml deploy/
bash hack/boilerplate/add-boilerplate.sh yaml minikube-operator-example/
bash hack/boilerplate/add-boilerplate.sh yaml config/
```
/lint
```release-note
NONE
```
=> Add license header to .go and .yaml

test/e2e-common.sh, test/e2e-upgrade-tests.sh
Fixes #
* Pin the upgrade to test against 0.13.0 manifest of serving. Issue with
the latest manifest will be resolved for next release. There is no need to call
`generate_latest_serving_manifest`.
* Replace the key word `all` with `deployment, pod, service, apiservice`.
* I will implement a better way to get the value for `LATEST_SERVING_RELEASE_VERSION` automatically, so far pin it to v0.12.1.
```release-note
```
=> Quick fix for upgrade prow job

Gopkg.lock, Gopkg.toml, pkg/reconciler/knativeserving/knativeserving_controller.go, test/resources/verify.go, vendor/github.com/manifestival/manifestival/client.go, vendor/github.com/manifestival/manifestival/dry.go, vendor/github.com/manifestival/manifestival/filter.go, vendor/github.com/manifestival/manifestival/manifestival.go, vendor/github.com/manifestival/manifestival/patch/patch.go, vendor/github.com/manifestival/manifestival/transform.go
Fixes a pretty gnarly bug where transformers using `Scheme.Convert` don't work.
This was exposed by #337
=> Bump to manifestival 0.4.0

Gopkg.lock, vendor/knative.dev/test-infra/scripts/release.sh
Upgrade to latest `test-infra`. Release process was blocked by https://github.com/knative/test-infra/issues/1804
Ran `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
Fixes #
*
*
*
```release-note
```
=> Upgrade to latest `test-infra`

Gopkg.lock, vendor/knative.dev/test-infra/scripts/release.sh
Upgrade to latest `test-infra`. Release process was blocked by https://github.com/knative/test-infra/issues/1804
Ran `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
Fixes #
*
*
*
```release-note
```
=> Upgrade to latest `test-infra`.

README.md
* By https://github.com/knative/serving-operator/pull/250, short name **ks** for the Knative Serving Operator CRD was removed from code. This PR is removing remaining **ks** in README.
```release-note
Remove the deprecated short name from README.
```
=> Remove the deprecated short name from README

test/e2e-common.sh, test/e2e-upgrade-tests.sh, test/upgrade/servingoperator_postupgrade_test.go
Fixes #
* After 0.13 release is cut-off, we need to change the upgrade prow job, by setting the previous
release to 0.13, and upgrading to the latest serving YAML.
```release-note
```
=> Update the upgrade to check upgrading from 0.13.0

pkg/reconciler/knativeserving/knativeserving_controller.go
This allows us to take advantage of the permissions granted to cluster admins
when performing cleanup. If the approach in https://github.com/knative/serving-operator/pull/291
is approved, this will become necessary. Additionally, it makes sense to remove roles as the final
step to allow human Operators to modify any resources they may have permissions on as a result of the Knative installation (that is, we should not remove any access until we are 'almost done' cleaning up).
/lint
* Delete roles and rolebindings as a final cleanup step.
```release-note
Delete roles and rolebindings as a final cleanup step.
```
=> Delete (Cluster)Role(Bindings) as a final cleanup step.

config/300-serving-v1alpha1-knativeserving-crd.yaml
A non-empty type for the root is required per
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema
Otherwise, the following status condition appears in the CRD on a
1.16+ cluster:
- lastTransitionTime: "2020-03-17T16:58:54Z"
message: 'spec.validation.openAPIV3Schema.type: Required value: must not be empty
at the root'
reason: Violations
status: "True"
type: NonStructuralSchema
=> Abide by first rule of structural schemas

config/300-serving-v1alpha1-knativeserving-crd.yaml
Alternatively, we could convert this v1beta1 CRD to v1.
=> Enable 'kubectl explain knativeserving' to work

pkg/reconciler/knativeserving/knativeserving_controller.go
This patch makes a tiny change to add log message when operator
deletes resources.
Currently there are no logs so it is difficult to debug when resources
are not deleted.
After this patch:
```
{"level":"info","ts":"2020-03-23T05:36:28.296Z","logger":"serving-operator.knativeserving-controller","caller":"knativeserving/knativeserving_controller.go:249","msg":"Deleting resources","commit":"d558b3a","knative.dev/controller":"knativeserving-controller"}
```
/lint
```release-note
NONE
```
=> Print log message when start deleting resources

pkg/reconciler/knativeserving/knativeserving_controller.go
This order, Roles -> RoleBindings -> The Rest, prevents the operand from
needing to structure their manifest such that this ordering exists, while
allowing the Operator to use the bootstrapping mechanism described in
https://github.com/knative/serving-operator/pull/291 to 'escalate' itself
into management of the Knative Serving installation without a *** clusterrole.
* Install roles, then rolebindings, then the remainder of the manifest.
```release-note
NONE
```
=> Install from the manifest in a strict(er) order.

config/role.yaml, config/role_binding.yaml
Fixes #282
#374  is a base of this, you can solely review the YAML here
(and not the reconciler change) though you're welcome to review
that as well.
By using the `escalate` verb on clusterroles, we allow the Operator
to have the ability to create any clusterrole. This prevents us from
needing to grant it `cluster-admin`.
Additionally, by having the Operator create an aggregated clusterrole
for itself (aggregating all clusteroles created by Knative Serving),
we pick up any permissions that the upstream dictate as necessary
by any component.
Any roles that are not created by upstream, but which are bound as
part of install are added with the `bind` verb to allow the Operator
to bind them without necessarily having the permissions they grant.
Some other permissions are needed to support …
=> Restrict RBAC for Operator

test/resources/knativeserving.go, test/resources/verify.go
Fixes #
* This PR fixed the broken retry mechanism, checking whether the deployments reach the desired state. It used to return `false, err`, which would run the check only once, but we need to return `false, nil`, till we reach the desired state. This PR made the correct changes for the retry mechanism.
```release-note
```
=> Fix the retry issue with deployment verification

OWNERS
Ali has done amazing work, even since he did not officially joined the Knative
community.
He is leading the effort in operator's release in operatorhub, contributing
across any aspects, testing the operators against multiple scenarios.
His strong review has also acted as a good goalkeeper of our repository.
Based on his general contribution during the past3 months, I would like
to add his as an approver.
Fixes #
*
*
*
```release-note
```
=> Add aliok as one approver of knative operator

pkg/reconciler/knativeserving/common/ha.go, pkg/reconciler/knativeserving/common/ha_test.go
If the operator has a HighAvailabiliy configuration and the replicas are set > 1, we probably want to adjust all HPAs to have at least as many minReplicas as specified in that HA config. An HPA being present is enough of a signal for us to assume that the component supports a HA configuration.
```release-note
Adjusts all HPAs to have at least the number of replicas specified by a potential HighAvailability configuration.
```
=> Respect HA Replicas setting in HPAs.

cmd/manager/main.go, minikube-operator-example/cmd/manager/main.go, pkg/reconciler/knativeserving/controller.go
To align with https://github.com/knative-sandbox/operator/pull/21 and to be able to use this controller as a "library" (to compile multiple operators into one binary), this moves the flag definition to the main.go file and passes the built config through.
```release-note
NONE
```
/assign @jcrossley3 @houshengbo
=> Pass config from main to the controller.
